name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ruff
      id: ruff
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Ruff
        setup-command: pip install ruff
        command: ruff check DoublyLinkedList.py
        timeout: 10
    - name: Code test
      id: code-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUFF_RESULTS: "${{steps.ruff.outputs.result}}"
        CODE-TEST_RESULTS: "${{steps.code-test.outputs.result}}"
      with:
        runners: ruff,code-test
